[package]
name = "zed-github-actions"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"

[lib]
path = "src/gh-actions-server.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
